name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 every day
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
